### ISSUE TITLE
Can't get FTX funding. At least as of version 1.9.3

### ISSUE THREAD

**Issue by ibmua** [bmoscon/cryptofeed#588]
**Describe the bug**
Can't get funding on FTX.
```
Task exception was never retrieved
future: <Task finished name='Task-5' coro=<FTX._funding() done, defined at /usr/local/lib/python3.8/dist-packages/cryptofeed-1.9.3-py3.8.egg/cryptofeed/exchange/ftx.py:196> exception=AttributeError("'HTTPAsyncConn' object has no attribute 'get'")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/cryptofeed-1.9.3-py3.8.egg/cryptofeed/exchange/ftx.py", line 213, in _funding
    data = await self.http_conn.get(f"https://ftx.com/api/funding_rates?future={pair}")
AttributeError: 'HTTPAsyncConn' object has no attribute 'get'

```

**Code**
Similar to https://github.com/bmoscon/cryptofeed/blob/master/examples/demo_ftx_funding.py , only fixed to work with 1.9.3 version, as "symbols" in that one don't seem to work with new one.

```
from cryptofeed import FeedHandler
from cryptofeed.callback import FundingCallback
from cryptofeed.defines import FUNDING
from cryptofeed.exchanges import FTX

from cryptofeed.symbols import Symbol
from cryptofeed.defines import CANDLES, BID, ASK, BLOCKCHAIN, COINBASE, FUNDING, GEMINI, L2_BOOK, L3_BOOK, OPEN_INTEREST, PERPETUAL, TICKER, TRADES, FUTURES_INDEX, BOOK_DELTA
from cryptofeed.callback import BookCallback, FundingCallback, TickerCallback, TradeCallback, FuturesIndexCallback, OpenInterestCallback
from cryptofeed import FeedHandler
from cryptofeed.defines import BID, ASK, L2_BOOK, L3_BOOK, TICKER, TRADES, FUNDING, LIQUIDATIONS
from cryptofeed.exchanges import OKEx, Binance, BinanceFutures, BinanceDelivery, Poloniex, Gateio, FTX

# Examples of some handlers for different updates. These currently don't do much.
# Handlers should conform to the patterns/signatures in callback.py
# Handlers can be normal methods/functions or async. The feedhandler is paused
# while the callbacks are being handled (unless they in turn await other functions or I/O)
# so they should be as lightweight as possible


symbol = Symbol('FLOW', 'USD', type=PERPETUAL)

async def funding(**kwargs):
    print(f"Funding Update for {kwargs['feed']}")
    print(kwargs)


def main():
    f = FeedHandler()
    f.add_feed(FTX(symbols=[symbol], channels=[FUNDING], callbacks={FUNDING: FundingCallback(funding)}))
    f.run()


if __name__ == '__main__':
    main()

```

**Operating System:**
Ubuntu

**Cryptofeed Version**
1.9.3

**Comment by bmoscon** [comment]
fixed - thanks for raising the issue!
